thementorship-tw/thementorship.tw

nextjs-app/app/core-values/page.tsx
nextjs-app/app/faq/page.tsx
nextjs-app/app/introduction/page.tsx
nextjs-app/app/page.tsx
nextjs-app/app/team/page.tsx

chore: create page template fot 1st milestone pages

---

nextjs-app/.eslintrc
nextjs-app/.prettierrc
nextjs-app/app/layout.tsx
nextjs-app/package.json
nextjs-app/pnpm-lock.yaml
package.json
pnpm-lock.yaml

chore: add eslint-config-prettier; adjust eslint settings to fix lint error
- Adding ESLint and Prettier rules ensures consistent coding standards and formatting rules across the project.
- Added ESLint extensions
- Defined Prettier rules
- Reviewed potential formatting changes introduced to avoid breaking the code.

chore: add ESLint and Prettier rules for code formmating

---

nextjs-app/components/pages/main/Partners.tsx
nextjs-app/tailwind.config.ts

- In previous PR, we move the components folder outside of app folder, but our tailwind config didn't add this new path
-
-

bug: add missing tailwind config

---

nextjs-app/app/about/overview/page.tsx
nextjs-app/app/about/philosophy/page.tsx
nextjs-app/app/about/team/page.tsx
nextjs-app/app/core-values/page.tsx
nextjs-app/app/introduction/page.tsx
nextjs-app/app/program-rules/page.tsx
nextjs-app/app/robots.ts
nextjs-app/app/sitemap.ts

- close #35 
- change route path
- change metadata
- change sitemap
-
-

refactor: change routes definition, metadata, sitemap based on 1st milestone

---

nextjs-app/app/about/overview/page.tsx
nextjs-app/components/pages/about/overview/ProgramIntroduction.tsx

- close #93 
- create `ProgramIntroduction` section on overview section
[
](url)
-

feat: create ProgramIntroduction section on overview page

---

nextjs-app/app/program-rules/page.tsx
nextjs-app/components/pages/main/WhatWeBring.tsx
nextjs-app/components/pages/program-rules/ProgramFees.tsx

- close #70 
- `ProgramFees` section
-

feat: create program fee section

---

nextjs-app/app/about/philosophy/page.tsx
nextjs-app/components/pages/about/philosophy/CorePhilosophy.tsx

- close #90 
| Mobile | Tablet | Desktop |
|------|------------|-------|
| <img width="502" alt="截圖 2025-01-25 晚上10 20 25" src="https://github.com/user-attachments/assets/6b4f2383-cd0a-4221-ad29-82bf8bebcc35" /> | <img width="829" alt="截圖 2025-01-25 晚上10 20 13" src="https://github.com/user-attachments/assets/ac5efd51-d0a6-4f34-bc40-05059eff2a7c" /> | <img width="1086" alt="截圖 2025-01-26 凌晨12 03 43" src="https://github.com/user-attachments/assets/09322c83-62a7-4d9d-9de2-8406c2477fca" />
|
-

feat: philosophy section in philosophy page

---

nextjs-app/app/layout.tsx
nextjs-app/app/page.tsx
nextjs-app/components/common/Header/Header.tsx
nextjs-app/components/pages/main/Banner.tsx

- close #108 
- header will hide when scroll down and show again when scroll up
- In the top of home page, we need the header to be transparent to mix with the background
https://github.com/user-attachments/assets/25db9084-f217-4d79-b6e8-7c6bc41905ef
-

feat: header enhancement

---

nextjs-app/components/pages/main/Partners.tsx

chore: layout refactor for partner icon

---

nextjs-app/components/common/ReviewCard.tsx
nextjs-app/components/pages/program-rules/ProgramFees.tsx

- Update UI for `ReviewCard` and `ProgramFee` components
- Review Card
- Program Fee
-

fix: update ui for ReviewCard and ProgramFee components

---

nextjs-app/components/common/FAQItem/index.tsx
nextjs-app/components/common/Header/Header.tsx
nextjs-app/components/pages/program-rules/Captains.tsx
nextjs-app/components/pages/team/ContentWithFilter.tsx
nextjs-app/package.json
nextjs-app/pnpm-lock.yaml
package.json

- scroll throttle
- captain section card heights are different
- FAQ need to be closed by default
-

feat: add enhancement from feedback

---

nextjs-app/app/about/overview/page.tsx
nextjs-app/app/about/philosophy/page.tsx
nextjs-app/app/about/team/page.tsx
nextjs-app/app/faq/page.tsx
nextjs-app/app/layout.tsx
nextjs-app/app/page.tsx
nextjs-app/app/program-rules/page.tsx
nextjs-app/components/common/Button/RegisterSailorButton.tsx
nextjs-app/components/pages/about/overview/MonthlyMeetingRoles.tsx
nextjs-app/components/pages/about/overview/ProgramIntroduction.tsx
nextjs-app/components/pages/about/overview/RecruitmentTargets.tsx
nextjs-app/constants/groups.ts
nextjs-app/constants/schedules.ts

- close #134 
- close #138 
- close #139 
- update meta title for each pages
- add canonical URL for each pages
- wording change
-

fix: metadata and wording

---

nextjs-app/components/common/Button/Button.tsx
nextjs-app/components/common/Footer.tsx

- close #127 
- Button hover styles (commit [#cc22a21](https://github.com/thementorship-tw/thementorship.tw/pull/142/commits/cc22a21ab387be40b2a9662551f65eb15dbe0d6d))
https://github.com/user-attachments/assets/244d8810-a67c-4807-a042-9a564796c195
- Copyright wording (commit [#a5fbbe1](https://github.com/thementorship-tw/thementorship.tw/pull/142/commits/a5fbbe198f20f2b2b21c69a40e441ca7b819a212))
-

Enhancement: button hover and copyright

---

nextjs-app/constants/pages/team.ts

chore: change captain job title

---

nextjs-app/app/layout.tsx
nextjs-app/app/page.tsx
nextjs-app/components/pages/main/Banner.tsx

enhancement: fix lighthouse issue in main page banner section

---

nextjs-app/components/pages/program-rules/ProgramFees.tsx
nextjs-app/components/pages/program-rules/Schedule/StepCard.tsx
nextjs-app/constants/pages/team.ts
nextjs-app/constants/schedules.ts

- Update text content
- Update Claire Title - 74704542520ea8e87db37f11d68ffdc3bc49111d
- Update ProgramFees text content - 71e2f5a1930fb132c833bbcdadb058ab805dfe9c
- Update Schedule text content - 1b4e1d3d9edbc4f96c99e42608b60d6bba7603a8
- http://localhost:3000/about/team
- http://localhost:3000/program-rules

feat: Update text content

---

.all-contributorsrc
README.md

feat: add contributor list

---

nextjs-app/constants/pages/team.ts

- close #168 
- Change "楊立偉" to "布萊恩"
-

fix: change captain Bryan's Chinese name

---

nextjs-app/components/pages/main/OurImpact.tsx

enhancement: our impact ux enhancement

---

nextjs-app/constants/schedules.tsx

- Update on May's status
- Navigator
- Sailor
-

feat: update program schedule phase
