.husky/pre-commit, commitlint.config.js, package.json, pnpm-lock.yaml
- To make sure commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- Installed `commitlint`
- Updated `husky` configuration to integrate with `commitlint`.
- Global Scope
- Verifies that commit messages follow the convention. 
- Commits will fail if the message does not comply with the rules.
=> chore: install commitlint and update related configuration

nextjs-app/app/dev-only/tailwind-demo/page.tsx, nextjs-app/design-system/data/token.json, nextjs-app/design-system/util/transferTokenToTailwindStyles.ts, nextjs-app/tailwind.config.ts
- close https://github.com/thementorship-tw/thementorship.tw/issues/24
- [b1c661c](https://github.com/thementorship-tw/thementorship.tw/pull/36/commits/b1c661cf8782b991000888889d511b59d9d00bdc): Update Design token (notion last updated at 2025/01/05 - [link](https://www.notion.so/Design-Token-1613af684bf880aa9e36d70db972e487))
- [3bf6041](https://github.com/thementorship-tw/thementorship.tw/pull/36/commits/3bf6041b4abe4b69795892d608d213e82d211a17), [3bf6041](https://github.com/thementorship-tw/thementorship.tw/pull/36/commits/3bf6041b4abe4b69795892d608d213e82d211a17) : Integrate design tokens for color 
- reference : https://tailwindcss.com/docs/customizing-colors#color-object-syntax
- [5f06ed2](https://github.com/thementorship-tw/thementorship.tw/pull/36/commits/5f06ed20009ab871785a2dc4b4 …
=> feat: Update design token & Integrate color to TailwindCSS configuration

nextjs-app/app/dev-only/tailwind-demo/page.tsx
Since I used template literals to compose CSS class names, 
Tailwind CSS couldn't interpret the corresponding styles.
ref: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
- Use static approach to write CSS class names
- page: http://localhost:3000/dev-only/tailwind-demo
=> fix: Tailwind CSS not generating corresponding styles on demo page

nextjs-app/app/faq/page.tsx, nextjs-app/app/not-found.tsx, nextjs-app/components/common/Breadcrumb.tsx, nextjs-app/components/pages/main/StayUpdated.tsx
- close #40 
- breadcrumb component
- remove all `PingFang_TC` font family
-
-
=> feat: breadcrumb common component

nextjs-app/app/about/overview/page.tsx, nextjs-app/app/about/philosophy/page.tsx, nextjs-app/app/about/team/page.tsx, nextjs-app/app/faq/page.tsx, nextjs-app/app/program-rules/page.tsx, nextjs-app/components/common/MarqueeTitle.tsx, nextjs-app/tailwind.config.ts
- close #41 
- `MarqueeTitle` component (for the animation, I refer to [this article](https://ithelp.ithome.com.tw/m/articles/10268962))
- based on the length of the text, we need to change the repeat time so that the speed for the animation could be similar on different pages
- add breadcrumb and marquee section to each pages
- Reference website provided by designer (https://school.kawa-sui.com/admission/)
- Check the animation effect with designer and she thinks it is good
https://github.com/user-attachments/assets/d99eb41a-f48c-4b13-aaa1-6f8b1c9dca20
-
-
=> feat: page title with animated text (marquee effect)

nextjs-app/components/common/Button.tsx, nextjs-app/components/common/InfoCard.tsx, nextjs-app/package.json, nextjs-app/pnpm-lock.yaml, package.json
- install `cva` and `tailwind-merge` library
- create `InfoCard` common component, we need to support the variants like below
Below is the sample, we can use props to control the variant of info card
-
-
=> feat: InfoCard common component & integrate cva and tailwind-merge

nextjs-app/app/program-rules/page.tsx, nextjs-app/components/pages/main/Partners.tsx, nextjs-app/components/pages/main/StayUpdated.tsx, nextjs-app/components/pages/program-rules/Benefits.tsx, nextjs-app/components/pages/program-rules/JoinUs.tsx, nextjs-app/components/pages/program-rules/SectionTitle.tsx
- close #63 
- add `SectionTitle` component in program rules page
- add `container` class to some section in previous PR
-
-
=> feat: section title component in program rules page

nextjs-app/.eslintrc, nextjs-app/app/about/overview/page.tsx, nextjs-app/app/about/philosophy/page.tsx, nextjs-app/app/about/team/page.tsx, nextjs-app/app/faq/page.tsx, nextjs-app/app/layout.tsx, nextjs-app/app/page.tsx, nextjs-app/app/program-rules/page.tsx, nextjs-app/components/common/Header/Header.tsx, nextjs-app/components/common/ReviewCard.tsx, nextjs-app/components/pages/faq/ContentWithFilter.tsx, nextjs-app/components/pages/main/SectionTitle.tsx, nextjs-app/components/pages/main/WhatWeBring.tsx, nextjs-app/components/pages/main/WhatWeDo.tsx, nextjs-app/components/pages/main/WhoWeAre.tsx, nextjs-app/components/pages/program-rules/SectionTitle.tsx, nextjs-app/package.json, nextjs-app/pnpm-lock.yaml, package.json
- close #82 
- add `pnpm run lint:fix` script
- integrate `eslint-plugin-import` for standardizing the import order rule in codebase
- the order is like the following
- `builtin`
- `external` (like `react`)
- `internal` (alias `@` should have higher priority, and for relative path, the order is `parent`, `sibling`, `index`)
- `type`
-
=> refactor: integrte import order linter and auto fix existing files

nextjs-app/design-system/data/token.json
Based on Figma, update design token
- Update design token
- Add new `font-size`
- Adjust `typography` font-weight
- Adjust `radius` value
- Adjust color `yellow` value
-
=> feat: Update design token

nextjs-app/components/pages/main/WhatWeBring.tsx
- Refactored the `WhatWeBring` section (commit [#f26de92](https://github.com/thementorship-tw/thementorship.tw/commit/f26de9246fe915e8559ab4822ad8cedca949b70b)):
- Integrated `SectionTitle` component
- Applied `container` className to the section container for consistent styling
- Added a `Rope` element to the `WhatWeBring` section (commit [#dc3b922](https://github.com/thementorship-tw/thementorship.tw/commit/dc3b9224beafb8acbfecdefd1699374dcc5d1b81))
- Desktop version
- Tablet version
- Mobile version
-
=> feat: add rope decoration

nextjs-app/app/about/overview/page.tsx, nextjs-app/components/common/PageNavigationCard.tsx, nextjs-app/components/pages/about/overview/GroupsIntro.tsx, nextjs-app/components/pages/about/overview/MonthlyMeetingRoles.tsx, nextjs-app/components/pages/about/overview/RecruitmentTargets.tsx
- close #94 
- `組別介紹` section in overview page
- create `PageNavigationCard` common component, which will also be used in philosophy page
- adjust padding in some sections
| Mobile | Tablet | Desktop |
|------|------------|-------|
| <img width="495" alt="截圖 2025-01-25 中午12 14 42" src="https://github.com/user-attachments/assets/86945d28-9f2c-48ee-82ea-cd7dfa2e03fb" /> | <img width="837" alt="截圖 2025-01-25 中午12 14 25" src="https://github.com/user-attachments/assets/f205f713-a563-4122-8d3a-1842862bdd8c" /> | <img width="1503" alt="截圖 2025-01-25 中午12 14 09" src="https://github.com/user-attachments/assets/fe8dd6ea-4708-438f-9a94-572098c6903d" /> |
-
=> feat: group intro section in overview page & PageNavigationCard common component

nextjs-app/components/common/Button/Button.tsx, nextjs-app/components/common/Button/RegisterNavigatorButton.tsx, nextjs-app/components/common/Button/RegisterSailorButton.tsx
- We will need to show disabled state before the registration starts
- change correct default padding for button
- add disabled style for `Button`, `RegisterNavigatorButton`, `RegisterSailorButton`
-
=> feat: disabled style for button component

nextjs-app/app/layout.tsx, nextjs-app/components/common/PostHogPageView.tsx, nextjs-app/package.json, nextjs-app/pnpm-lock.yaml, nextjs-app/providers/CSPostHogProvider.tsx, package.json
- close #123 
- I choose [PostHog](https://posthog.com) as our solution, here is the reasons
- Real-time event tracking → No delays in data processing.
- Session replay → Watch user interactions directly.
-  Feature flags & A/B testing → Built-in for product teams.
- Developer-friendly API → Easier integration & customization.
To sum up, `PostHog` is ideal for product analytics, while GA4 is better for marketing & SEO tracking, although we only need  few features now, it will provide more possibilities for us in the future
- For the integration code, I mainly refer to [the official doc](https://posthog.com/docs/libraries/next-js)
- Only enable the analytics in prod mode, the screenshot is for demo purpose 
https://github.com/user-attachments/assets/48768210-17aa-4ffd-9015-7b8380121f33
=> feat: integrate posthog

nextjs-app/components/pages/about/philosophy/ProgramIntroduction.tsx, nextjs-app/components/pages/main/Banner.tsx
- close #132 
- also remove the `priority` prop on boat.png because I just notice that only lg screen need this image. If we add this property, all the device will preload the image
-
=> enhancement: show boat icon on each device & remove priority prop on boat png

nextjs-app/components/common/Header/Accordion.tsx, nextjs-app/components/common/Header/HamburgerButton.tsx, nextjs-app/components/common/Header/MobileCollapseMenu.tsx
- close https://github.com/thementorship-tw/thementorship.tw/issues/128
https://github.com/user-attachments/assets/11a56dfc-fae0-4b90-b1b7-919a54df35ff
To be confirmed ?
- http://localhost:3000/
=> fix: mobile nav menu design review

nextjs-app/components/pages/program-rules/Schedule/DetailCard.tsx, nextjs-app/constants/schedules.tsx, nextjs-app/types/schedule.ts
- Update schedules in Program Rules page based on Figma ([Navigator](https://www.figma.com/design/2lrWJUBMqoTA7U7r6L8Fsq/UI?node-id=690-32153&m=dev) & [Sailor](https://www.figma.com/design/2lrWJUBMqoTA7U7r6L8Fsq/UI?node-id=339-20298&m=dev))
- Navigator
- Sailor
- `/program-rules`
=> feat: update schedules in Program Rules page

nextjs-app/components/common/MarqueeContainer.tsx, nextjs-app/components/common/ReviewCard.tsx, nextjs-app/tailwind.config.ts
- close #131 
1. Unify the height for review cards within the same row
2. Reduce the speed of the marquee animation
3. Pause the marquee animation on hover
https://github.com/user-attachments/assets/6159d361-f5f4-42eb-811f-ad2b1cf3a584
- `/`
- `/program-rules`
=> Feat: 131 update testimonials animation

nextjs-app/components/pages/program-rules/Schedule/DetailCard.tsx, nextjs-app/components/pages/program-rules/Schedule/detailCardStyles.ts, nextjs-app/constants/schedules.tsx
- Update the schedule status
- Adjust `DetailCard` styles to prevent information wrapping on desktop version.
| Role       | Before  | After  |
|------------|--------|--------|
| Sailor     | <img width="300" alt="Before" src="https://github.com/user-attachments/assets/3e38f93a-0f07-427e-b53c-401d43a8a688" /> | <img width="300" alt="After" src="https://github.com/user-attachments/assets/bf6ba2dc-c92e-4785-8a97-6a8579c99f92" /> |
| Navigator  | <img width="300" alt="Before" src="https://github.com/user-attachments/assets/f31cc965-c109-440c-8d95-23368aa652e8" /> | <img width="300" alt="After" src="https://github.com/user-attachments/assets/af3f92e3-2ae7-4ec0-8e35-e5a3021f09d4" /> |
- `/program-rules`
=> Update DetailCard styles & Schedule status

nextjs-app/constants/schedules.tsx
-
- Update program schedule status – April is the current ongoing month.
- `/program-rules`
=> feat: update program schedule status

nextjs-app/constants/schedules.tsx
- Update the infomation of the keynote talks
- Remove the tag and update the date of the lecture
- /program-rules
=> feat: update program schedule in May

nextjs-app/utils/activity.ts
- The time display was affected by the user's local timezone.
- However, the intended behavior is to display times in `Taipei Time`.
- Updated the time formatting logic to explicitly display time in the Asia/Taipei timezone.
- `/activity`
=> fix: correct timezone display on Activity page
